services:
  onnx_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onnx_pipeline_container
    cpus: 2.0
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/app/host_data  # To save outputs if needed
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G 
    command: /bin/bash -c "./run_with_display.sh"
